### ISSUE TITLE
fix: Same key warn in `<LinksAccordion />`

### ISSUE THREAD

**Issue by taichi221228** [taichi221228/taichi221228#198]
```log
links-accordion.tsx:19 QWIK WARN JSXError: Multiple JSX sibling nodes with the same key.
This is likely caused by missing a custom key in a for loop
    at _jsxQ (core.mjs?v=a58d054c:2529:20)
    at links-accordion.tsx:21:13
    at Array.map (<anonymous>)
    at AsyncFunction.LinksAccordion_component_kRNV3Dxnngo [as resolved] (links-accordion.tsx:20:12)
    at AsyncFunction.invokeApply (core.mjs?v=a58d054c:4474:26)
    at AsyncFunction.invoke (core.mjs?v=a58d054c:4466:24)
    at core.mjs?v=a58d054c:8574:35
    at async Promise.all (contact-me/index 0)
    at async Promise.all (contact-me/index 1)
    at async Promise.all (contact-me/index 1)
logWarn @ core.mjs?v=a58d054c:125
logOnceWarn @ core.mjs?v=a58d054c:119
(anonymous) @ core.mjs?v=a58d054c:2675
(anonymous) @ core.mjs?v=a58d054c:2668
invokeApply @ core.mjs?v=a58d054c:4474
invoke @ core.mjs?v=a58d054c:4466
validateJSXNode @ core.mjs?v=a58d054c:2635
_jsxQ @ core.mjs?v=a58d054c:2533
LinksAccordion_component_kRNV3Dxnngo @ links-accordion.tsx:19
invokeApply @ core.mjs?v=a58d054c:4474
invoke @ core.mjs?v=a58d054c:4466
(anonymous) @ core.mjs?v=a58d054c:8574
Promise.then (async)
maybeThen @ core.mjs?v=a58d054c:460
(anonymous) @ core.mjs?v=a58d054c:8560
(anonymous) @ core.mjs?v=a58d054c:1392
safeCall @ core.mjs?v=a58d054c:447
executeComponent @ core.mjs?v=a58d054c:1392
renderComponent @ core.mjs?v=a58d054c:2854
createElm @ core.mjs?v=a58d054c:5397
addChildren @ core.mjs?v=a58d054c:5204
smartUpdateChildren @ core.mjs?v=a58d054c:4824
(anonymous) @ core.mjs?v=a58d054c:2873
maybeThen @ core.mjs?v=a58d054c:460
(anonymous) @ core.mjs?v=a58d054c:2869
Promise.then (async)
maybeThen @ core.mjs?v=a58d054c:460
renderComponent @ core.mjs?v=a58d054c:2854
createElm @ core.mjs?v=a58d054c:5397
(anonymous) @ core.mjs?v=a58d054c:5454
createElm @ core.mjs?v=a58d054c:5454
addChildren @ core.mjs?v=a58d054c:5204
smartUpdateChildren @ core.mjs?v=a58d054c:4824
(anonymous) @ core.mjs?v=a58d054c:2873
maybeThen @ core.mjs?v=a58d054c:460
(anonymous) @ core.mjs?v=a58d054c:2869
Promise.then (async)
maybeThen @ core.mjs?v=a58d054c:460
renderComponent @ core.mjs?v=a58d054c:2854
createElm @ core.mjs?v=a58d054c:5397
(anonymous) @ core.mjs?v=a58d054c:5454
createElm @ core.mjs?v=a58d054c:5454
(anonymous) @ core.mjs?v=a58d054c:5454
createElm @ core.mjs?v=a58d054c:5454
addChildren @ core.mjs?v=a58d054c:5204
smartUpdateChildren @ core.mjs?v=a58d054c:4824
(anonymous) @ core.mjs?v=a58d054c:2873
maybeThen @ core.mjs?v=a58d054c:460
(anonymous) @ core.mjs?v=a58d054c:2869
Promise.then (async)
maybeThen @ core.mjs?v=a58d054c:460
renderComponent @ core.mjs?v=a58d054c:2854
createElm @ core.mjs?v=a58d054c:5397
diffChildren @ core.mjs?v=a58d054c:4897
smartUpdateChildren @ core.mjs?v=a58d054c:4818
(anonymous) @ core.mjs?v=a58d054c:5196
renderContentProjection @ core.mjs?v=a58d054c:5179
diffVnode @ core.mjs?v=a58d054c:5131
diffChildren @ core.mjs?v=a58d054c:4863
smartUpdateChildren @ core.mjs?v=a58d054c:4818
diffVnode @ core.mjs?v=a58d054c:5145
diffChildren @ core.mjs?v=a58d054c:4863
smartUpdateChildren @ core.mjs?v=a58d054c:4818
(anonymous) @ core.mjs?v=a58d054c:2873
maybeThen @ core.mjs?v=a58d054c:460
(anonymous) @ core.mjs?v=a58d054c:2869
Promise.then (async)
maybeThen @ core.mjs?v=a58d054c:460
renderComponent @ core.mjs?v=a58d054c:2854
renderMarked @ core.mjs?v=a58d054c:3534
await in renderMarked (async)
postRendering @ core.mjs?v=a58d054c:3601
await in postRendering (async)
renderMarked @ core.mjs?v=a58d054c:3555
await in renderMarked (async)
(anonymous) @ core.mjs?v=a58d054c:3488
(anonymous) @ core.mjs?v=a58d054c:354
setTimeout (async)
(anonymous) @ core.mjs?v=a58d054c:353
nextTick @ core.mjs?v=a58d054c:352
scheduleFrame @ core.mjs?v=a58d054c:3488
notifyTask @ core.mjs?v=a58d054c:3483
notifyChange @ core.mjs?v=a58d054c:3418
$notifySubs$ @ core.mjs?v=a58d054c:8483
set value @ core.mjs?v=a58d054c:4641
QwikCityProvider_component_goto_fX0bDjeJa0E @ index.qwik.mjs:718
invokeApply @ core.mjs?v=a58d054c:4474
invoke @ core.mjs?v=a58d054c:4466
(anonymous) @ core.mjs?v=a58d054c:8574
Promise.then (async)
maybeThen @ core.mjs?v=a58d054c:460
(anonymous) @ core.mjs?v=a58d054c:8560
qrl @ core.mjs?v=a58d054c:8521
Link_component_handleClick_pIf0khHUxfY @ index.qwik.mjs:1055
dispatch @ contact-me/:4313
await in dispatch (async)
processDocumentEvent @ contact-me/:4335
Show 83 more frames
Show less
```

**Comment by taichi221228** [comment]
relate: #199
